services:
  - type: web
    name: recicla-contigo-backend
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: recicla-contigo-db
          property: connectionString
      - key: JAVA_OPTS
        value: "-Xmx512m -Xms256m"
      - key: SPRING_PROFILES_ACTIVE
        value: prod

databases:
  - name: recicla-contigo-db
    databaseName: recicla_contigo_db
    user: recicla_contigo_user
    plan: free
    region: oregon

